---
- name: PM-Wireguard
  hosts: wireguard
  become: true
  gather_facts: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Базовая настройка сервера ===================
      include_role:
        name: role-base-config
      when: (not flush) and (not flush_data)
        
  tasks:
    - name: Wireguard ===================================
      include_role:
        name: role-wireguard
    - name: Adguard =====================================
      include_role:
        name: role-adguard
    - name: DNScrypt ====================================
      include_role:
        name: role-dnscrypt
    - name: Unboud ======================================
      include_role:
        name: role-unbound

    - name: Перезагрузка сервера
      ansible.builtin.reboot:
        reboot_timeout: 3600

    - name: Installed
      debug:
        msg:
          - "################################################################################################################"
          - "Установка завершена успешно!"
          - "    Для настройки подключения воспользуйтесь своим telegram ботом"
          - "    Консоль администратора AdGuardHome доступна по пути {{ wireguard_subnet }}1 только при подключении через VPN"
          - "################################################################################################################"
      when: (not flush) and (not flush_data)

    - name: Removed
      debug:
        msg:
          - "################################################################################################################"
          - "Удаление завершена успешно!"
          - "################################################################################################################"
      when: (flush) or (flush_data)
