---
- name: PM-Wireguard
  hosts: wireguard
  become: true
  gather_facts: true
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Базовая настройка сервера ===================
      include_role:
        name: role-base-config
        
  tasks:
    - name: Adguard =====================================
      include_role:
        name: role-adguard
    - name: Wireguard ===================================
      include_role:
        name: role-wireguard
    # - name: DNScrypt ====================================
    #   include_role:
    #     name: role-dnscrypt
    - name: Unbound =====================================
      include_role:
        name: role-unbound

    - name: Installed
      debug:
        msg:
          - "################################################################################################################"
          - "Установка завершена успешно!"
          - "    Для настройки подключения воспользуйтесь своим telegram ботом"
          - "    Консоль администратора AdGuardHome доступна по пути {{ wireguard_subnet }}1 только при подключении через VPN"
          - "################################################################################################################"
      when: (not flush_all)

    - name: Removed
      debug:
        msg:
          - "################################################################################################################"
          - "Удаление завершена успешно!"
          - "################################################################################################################"
      when: (flush_all)
