---
# - name: CertBot
#   include: certbot.yml

- name: Статус AdGuardHome
  systemd:
    name: "AdGuardHome"
  register: adguardhome_status

- name: Удаление AdGuardHome
  include: uninstall.yml
  when: (flush) and (not adguardhome_status.status.ActiveState == 'inactive')

- name: Установка AdGuardHome
  include: install.yml
  when: (not flush) and (adguardhome_status.status.ActiveState == 'inactive')
...