---
- name: AdGuardHome остановлен и убран из автозагрузки
  systemd:
    name: agh
    daemon_reload: true
    state: stopped
    enabled: false
    masked: no
  ignore_errors: true

- name: Service файл удалён
  become: true
  file:
    path: /systemd/system/agh
    state: absent

- name: AdGuardHome убран из $PATH
  file:
    path: /usr/bin/agh
    state: absent

- name: AdGuardHome удалён
  become: true
  file:
    path: /opt/agh
    state: absent
...